export enum MessageType {
  ExamEvent = "EXAM_EVENT",
  ACTION = "ACTION",
  SUBMISSION = "SUBMISSION",
}

export enum ExamEventType {
  CONNECT_RES = "CONNECT_RES",
  LOGOUT = "LOGOUT",
  LOGOUT_RES = "LOGOUT_RES",
  TAB_SWITCH = "TAB_SWITCH",
  TAB_SWITCH_RES = "TAB_SWITCH_RES",
  ERROR_PROCESSING_REQUEST = "ERROR_PROCESSING_REQUEST",
}

export enum ActionType {
  EXAM_QUESTION_REQ = "EXAM_QUESTION_REQ",
  EXAM_QUESTION_RES = "EXAM_QUESTION_RES",
  START_EXAM_REQ = "START_EXAM_REQ",
  START_EXAM_RES = "START_EXAM_RES",
  SUBMIT_EXAM_REQ = "SUBMIT_EXAM_REQ",
  SUBMIT_EXAM_RES = "SUBMIT_EXAM_RES",
  PING = "PING",
  PONG = "PONG",
  FORCE_LOGOUT = "FORCE_LOGOUT",
  ERROR_PROCESSING_REQUEST = "ERROR_PROCESSING_REQUEST",
}

export enum SubmissionType {
  MULTIPLE_CHOICE_SUBMISSION = "MULTIPLE_CHOICE_SUBMISSION",
  MULTIPLE_CHOICE_SUBMISSION_RES = "MULTIPLE_CHOICE_SUBMISSION_RES",
  PROGRAMMING_SUBMISSION = "PROGRAMMING_SUBMISSION",
  PROGRAMMING_SUBMISSION_RES = "PROGRAMMING_SUBMISSION_RES",
  UPDATE_TIME_SPENT = "UPDATE_TIME_SPENT",
  ERROR_PROCESSING_REQUEST = "ERROR_PROCESSING_REQUEST",
}
